"""Add generated_lessons table

Revision ID: bb89556edf66
Revises: 73d63f778eee
Create Date: 2026-01-07 21:27:15.985953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb89556edf66'
down_revision: Union[str, Sequence[str], None] = '73d63f778eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_lessons_id'), 'generated_lessons', ['id'], unique=False)
    op.create_index(op.f('ix_generated_lessons_topic'), 'generated_lessons', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_lessons_topic'), table_name='generated_lessons')
    op.drop_index(op.f('ix_generated_lessons_id'), table_name='generated_lessons')
    op.drop_table('generated_lessons')
    # ### end Alembic commands ###
