"""Add MinIO fields to documents

Revision ID: fe378a87e6a4
Revises: b3234eb06669
Create Date: 2026-01-07 19:17:15.133479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe378a87e6a4'
down_revision: Union[str, Sequence[str], None] = 'b3234eb06669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('bucket_name', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('storage_path', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'is_processed')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'bucket_name')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'mime_type')
    # ### end Alembic commands ###
